/**
 * The countries there are.
 *
 * ISO 3166-1 alpha-2: the two-letter codes every passport, visa form,
 * university portal and the site's own flags run on. A destination can only
 * be one of these. "In admin we can add any country with any code" — a code
 * that is not a country's is a row the finder cannot put a flag on and a
 * university page cannot be filed under, and a code that IS a country's but
 * with another name typed beside it renamed the country that was already
 * there.
 *
 * The first name in each list is the one people type and the one the site
 * shows; the rest are the other names the same country goes by — ISO's own
 * longer forms and the everyday ones (UK, USA, Holland) — so an admin who
 * types "UK" is told it is GB rather than refused.
 *
 * Generated from the ISO list; a change to a country's name is a change here.
 */
const ISO = {
  AD: ["Andorra", "Principality of Andorra"],
  AE: ["United Arab Emirates", "UAE"],
  AF: ["Afghanistan", "Islamic Republic of Afghanistan"],
  AG: ["Antigua and Barbuda"],
  AI: ["Anguilla"],
  AL: ["Albania", "Republic of Albania"],
  AM: ["Armenia", "Republic of Armenia"],
  AO: ["Angola", "Republic of Angola"],
  AQ: ["Antarctica"],
  AR: ["Argentina", "Argentine Republic"],
  AS: ["American Samoa"],
  AT: ["Austria", "Republic of Austria"],
  AU: ["Australia"],
  AW: ["Aruba"],
  AX: ["Åland Islands"],
  AZ: ["Azerbaijan", "Republic of Azerbaijan"],
  BA: ["Bosnia and Herzegovina", "Republic of Bosnia and Herzegovina"],
  BB: ["Barbados"],
  BD: ["Bangladesh", "People's Republic of Bangladesh"],
  BE: ["Belgium", "Kingdom of Belgium"],
  BF: ["Burkina Faso"],
  BG: ["Bulgaria", "Republic of Bulgaria"],
  BH: ["Bahrain", "Kingdom of Bahrain"],
  BI: ["Burundi", "Republic of Burundi"],
  BJ: ["Benin", "Republic of Benin"],
  BL: ["Saint Barthélemy"],
  BM: ["Bermuda"],
  BN: ["Brunei", "Brunei Darussalam"],
  BO: ["Bolivia", "Bolivia, Plurinational State of", "Plurinational State of Bolivia"],
  BQ: ["Caribbean Netherlands", "Bonaire, Sint Eustatius and Saba"],
  BR: ["Brazil", "Federative Republic of Brazil"],
  BS: ["Bahamas", "Commonwealth of the Bahamas"],
  BT: ["Bhutan", "Kingdom of Bhutan"],
  BV: ["Bouvet Island"],
  BW: ["Botswana", "Republic of Botswana"],
  BY: ["Belarus", "Republic of Belarus"],
  BZ: ["Belize"],
  CA: ["Canada"],
  CC: ["Cocos (Keeling) Islands"],
  CD: ["DR Congo", "Congo, The Democratic Republic of the"],
  CF: ["Central African Republic"],
  CG: ["Congo", "Republic of the Congo"],
  CH: ["Switzerland", "Swiss Confederation"],
  CI: ["Ivory Coast", "Côte d'Ivoire", "Republic of Côte d'Ivoire"],
  CK: ["Cook Islands"],
  CL: ["Chile", "Republic of Chile"],
  CM: ["Cameroon", "Republic of Cameroon"],
  CN: ["China", "People's Republic of China"],
  CO: ["Colombia", "Republic of Colombia"],
  CR: ["Costa Rica", "Republic of Costa Rica"],
  CU: ["Cuba", "Republic of Cuba"],
  CV: ["Cape Verde", "Cabo Verde", "Republic of Cabo Verde"],
  CW: ["Curaçao"],
  CX: ["Christmas Island"],
  CY: ["Cyprus", "Republic of Cyprus"],
  CZ: ["Czech Republic", "Czechia"],
  DE: ["Germany", "Federal Republic of Germany"],
  DJ: ["Djibouti", "Republic of Djibouti"],
  DK: ["Denmark", "Kingdom of Denmark"],
  DM: ["Dominica", "Commonwealth of Dominica"],
  DO: ["Dominican Republic"],
  DZ: ["Algeria", "People's Democratic Republic of Algeria"],
  EC: ["Ecuador", "Republic of Ecuador"],
  EE: ["Estonia", "Republic of Estonia"],
  EG: ["Egypt", "Arab Republic of Egypt"],
  EH: ["Western Sahara"],
  ER: ["Eritrea", "the State of Eritrea"],
  ES: ["Spain", "Kingdom of Spain"],
  ET: ["Ethiopia", "Federal Democratic Republic of Ethiopia"],
  FI: ["Finland", "Republic of Finland"],
  FJ: ["Fiji", "Republic of Fiji"],
  FK: ["Falkland Islands", "Falkland Islands (Malvinas)"],
  FM: ["Micronesia", "Federated States of Micronesia", "Micronesia, Federated States of"],
  FO: ["Faroe Islands"],
  FR: ["France", "French Republic"],
  GA: ["Gabon", "Gabonese Republic"],
  GB: ["United Kingdom", "Britain", "England", "Great Britain", "UK", "United Kingdom of Great Britain and Northern Ireland"],
  GD: ["Grenada"],
  GE: ["Georgia"],
  GF: ["French Guiana"],
  GG: ["Guernsey"],
  GH: ["Ghana", "Republic of Ghana"],
  GI: ["Gibraltar"],
  GL: ["Greenland"],
  GM: ["Gambia", "Republic of the Gambia"],
  GN: ["Guinea", "Republic of Guinea"],
  GP: ["Guadeloupe"],
  GQ: ["Equatorial Guinea", "Republic of Equatorial Guinea"],
  GR: ["Greece", "Hellenic Republic"],
  GS: ["South Georgia and the South Sandwich Islands"],
  GT: ["Guatemala", "Republic of Guatemala"],
  GU: ["Guam"],
  GW: ["Guinea-Bissau", "Republic of Guinea-Bissau"],
  GY: ["Guyana", "Republic of Guyana"],
  HK: ["Hong Kong", "Hong Kong Special Administrative Region of China"],
  HM: ["Heard Island and McDonald Islands"],
  HN: ["Honduras", "Republic of Honduras"],
  HR: ["Croatia", "Republic of Croatia"],
  HT: ["Haiti", "Republic of Haiti"],
  HU: ["Hungary"],
  ID: ["Indonesia", "Republic of Indonesia"],
  IE: ["Ireland"],
  IL: ["Israel", "State of Israel"],
  IM: ["Isle of Man"],
  IN: ["India", "Republic of India"],
  IO: ["British Indian Ocean Territory"],
  IQ: ["Iraq", "Republic of Iraq"],
  IR: ["Iran", "Iran, Islamic Republic of", "Islamic Republic of Iran"],
  IS: ["Iceland", "Republic of Iceland"],
  IT: ["Italy", "Italian Republic"],
  JE: ["Jersey"],
  JM: ["Jamaica"],
  JO: ["Jordan", "Hashemite Kingdom of Jordan"],
  JP: ["Japan"],
  KE: ["Kenya", "Republic of Kenya"],
  KG: ["Kyrgyzstan", "Kyrgyz Republic"],
  KH: ["Cambodia", "Kingdom of Cambodia"],
  KI: ["Kiribati", "Republic of Kiribati"],
  KM: ["Comoros", "Union of the Comoros"],
  KN: ["Saint Kitts and Nevis"],
  KP: ["North Korea", "Democratic People's Republic of Korea", "Korea, Democratic People's Republic of"],
  KR: ["South Korea", "Korea", "Korea, Republic of", "Republic of Korea"],
  KW: ["Kuwait", "State of Kuwait"],
  KY: ["Cayman Islands"],
  KZ: ["Kazakhstan", "Republic of Kazakhstan"],
  LA: ["Laos", "Lao People's Democratic Republic"],
  LB: ["Lebanon", "Lebanese Republic"],
  LC: ["Saint Lucia"],
  LI: ["Liechtenstein", "Principality of Liechtenstein"],
  LK: ["Sri Lanka", "Democratic Socialist Republic of Sri Lanka"],
  LR: ["Liberia", "Republic of Liberia"],
  LS: ["Lesotho", "Kingdom of Lesotho"],
  LT: ["Lithuania", "Republic of Lithuania"],
  LU: ["Luxembourg", "Grand Duchy of Luxembourg"],
  LV: ["Latvia", "Republic of Latvia"],
  LY: ["Libya"],
  MA: ["Morocco", "Kingdom of Morocco"],
  MC: ["Monaco", "Principality of Monaco"],
  MD: ["Moldova", "Moldova, Republic of", "Republic of Moldova"],
  ME: ["Montenegro"],
  MF: ["Saint Martin", "Saint Martin (French part)"],
  MG: ["Madagascar", "Republic of Madagascar"],
  MH: ["Marshall Islands", "Republic of the Marshall Islands"],
  MK: ["North Macedonia", "Republic of North Macedonia"],
  ML: ["Mali", "Republic of Mali"],
  MM: ["Myanmar", "Republic of Myanmar"],
  MN: ["Mongolia"],
  MO: ["Macao", "Macao Special Administrative Region of China"],
  MP: ["Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands"],
  MQ: ["Martinique"],
  MR: ["Mauritania", "Islamic Republic of Mauritania"],
  MS: ["Montserrat"],
  MT: ["Malta", "Republic of Malta"],
  MU: ["Mauritius", "Republic of Mauritius"],
  MV: ["Maldives", "Republic of Maldives"],
  MW: ["Malawi", "Republic of Malawi"],
  MX: ["Mexico", "United Mexican States"],
  MY: ["Malaysia"],
  MZ: ["Mozambique", "Republic of Mozambique"],
  NA: ["Namibia", "Republic of Namibia"],
  NC: ["New Caledonia"],
  NE: ["Niger", "Republic of the Niger"],
  NF: ["Norfolk Island"],
  NG: ["Nigeria", "Federal Republic of Nigeria"],
  NI: ["Nicaragua", "Republic of Nicaragua"],
  NL: ["Netherlands", "Holland", "Kingdom of the Netherlands"],
  NO: ["Norway", "Kingdom of Norway"],
  NP: ["Nepal", "Federal Democratic Republic of Nepal"],
  NR: ["Nauru", "Republic of Nauru"],
  NU: ["Niue"],
  NZ: ["New Zealand"],
  OM: ["Oman", "Sultanate of Oman"],
  PA: ["Panama", "Republic of Panama"],
  PE: ["Peru", "Republic of Peru"],
  PF: ["French Polynesia"],
  PG: ["Papua New Guinea", "Independent State of Papua New Guinea"],
  PH: ["Philippines", "Republic of the Philippines"],
  PK: ["Pakistan", "Islamic Republic of Pakistan"],
  PL: ["Poland", "Republic of Poland"],
  PM: ["Saint Pierre and Miquelon"],
  PN: ["Pitcairn Islands", "Pitcairn"],
  PR: ["Puerto Rico"],
  PS: ["Palestine", "Palestine, State of", "the State of Palestine"],
  PT: ["Portugal", "Portuguese Republic"],
  PW: ["Palau", "Republic of Palau"],
  PY: ["Paraguay", "Republic of Paraguay"],
  QA: ["Qatar", "State of Qatar"],
  RE: ["Réunion"],
  RO: ["Romania"],
  RS: ["Serbia", "Republic of Serbia"],
  RU: ["Russia", "Russian Federation"],
  RW: ["Rwanda", "Rwandese Republic"],
  SA: ["Saudi Arabia", "Kingdom of Saudi Arabia"],
  SB: ["Solomon Islands"],
  SC: ["Seychelles", "Republic of Seychelles"],
  SD: ["Sudan", "Republic of the Sudan"],
  SE: ["Sweden", "Kingdom of Sweden"],
  SG: ["Singapore", "Republic of Singapore"],
  SH: ["Saint Helena", "Saint Helena, Ascension and Tristan da Cunha"],
  SI: ["Slovenia", "Republic of Slovenia"],
  SJ: ["Svalbard and Jan Mayen"],
  SK: ["Slovakia", "Slovak Republic"],
  SL: ["Sierra Leone", "Republic of Sierra Leone"],
  SM: ["San Marino", "Republic of San Marino"],
  SN: ["Senegal", "Republic of Senegal"],
  SO: ["Somalia", "Federal Republic of Somalia"],
  SR: ["Suriname", "Republic of Suriname"],
  SS: ["South Sudan", "Republic of South Sudan"],
  ST: ["São Tomé and Príncipe", "Democratic Republic of Sao Tome and Principe", "Sao Tome and Principe"],
  SV: ["El Salvador", "Republic of El Salvador"],
  SX: ["Sint Maarten", "Sint Maarten (Dutch part)"],
  SY: ["Syria", "Syrian Arab Republic"],
  SZ: ["Eswatini", "Kingdom of Eswatini"],
  TC: ["Turks and Caicos Islands"],
  TD: ["Chad", "Republic of Chad"],
  TF: ["French Southern Territories"],
  TG: ["Togo", "Togolese Republic"],
  TH: ["Thailand", "Kingdom of Thailand"],
  TJ: ["Tajikistan", "Republic of Tajikistan"],
  TK: ["Tokelau"],
  TL: ["Timor-Leste", "Democratic Republic of Timor-Leste"],
  TM: ["Turkmenistan"],
  TN: ["Tunisia", "Republic of Tunisia"],
  TO: ["Tonga", "Kingdom of Tonga"],
  TR: ["Türkiye", "Republic of Türkiye"],
  TT: ["Trinidad and Tobago", "Republic of Trinidad and Tobago"],
  TV: ["Tuvalu"],
  TW: ["Taiwan", "Taiwan, Province of China"],
  TZ: ["Tanzania", "Tanzania, United Republic of", "United Republic of Tanzania"],
  UA: ["Ukraine"],
  UG: ["Uganda", "Republic of Uganda"],
  UM: ["US Minor Outlying Islands", "United States Minor Outlying Islands"],
  US: ["United States", "America", "USA", "United States of America"],
  UY: ["Uruguay", "Eastern Republic of Uruguay"],
  UZ: ["Uzbekistan", "Republic of Uzbekistan"],
  VA: ["Vatican City", "Holy See (Vatican City State)"],
  VC: ["Saint Vincent and the Grenadines"],
  VE: ["Venezuela", "Bolivarian Republic of Venezuela", "Venezuela, Bolivarian Republic of"],
  VG: ["British Virgin Islands", "Virgin Islands, British"],
  VI: ["US Virgin Islands", "Virgin Islands of the United States", "Virgin Islands, U.S."],
  VN: ["Vietnam", "Socialist Republic of Viet Nam", "Viet Nam"],
  VU: ["Vanuatu", "Republic of Vanuatu"],
  WF: ["Wallis and Futuna"],
  WS: ["Samoa", "Independent State of Samoa"],
  YE: ["Yemen", "Republic of Yemen"],
  YT: ["Mayotte"],
  ZA: ["South Africa", "Republic of South Africa"],
  ZM: ["Zambia", "Republic of Zambia"],
  ZW: ["Zimbabwe", "Republic of Zimbabwe"],
};

const canon = s => String(s || '').trim().toLowerCase().replace(/\s+/g, ' ');

/* The country a code names, or null. */
function byCode(code) {
  const c = String(code || '').toUpperCase().replace(/[^A-Z]/g, '');
  return ISO[c] ? { code: c, name: ISO[c][0], names: ISO[c] } : null;
}

/* The country a NAME names — "Germany", "UK", "Holland" — or null. */
function byName(name) {
  const n = canon(name);
  if (!n) return null;
  for (const code of Object.keys(ISO)) {
    if (ISO[code].some(x => canon(x) === n)) return byCode(code);
  }
  return null;
}

/* Two regional-indicator letters make the flag; every platform draws it. */
function flagOf(code) {
  const c = String(code || '').toUpperCase();
  if (!/^[A-Z]{2}$/.test(c)) return '';
  return String.fromCodePoint(...[...c].map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
}

/* Code → common name, for a client that wants to offer the list. */
function all() {
  return Object.keys(ISO).map(code => ({ code, name: ISO[code][0], flag: flagOf(code) }));
}

module.exports = { ISO, byCode, byName, flagOf, all };
