'use strict';
/**
 * The demo account.
 *
 * Created once, on the first run, so the portal has something in it before
 * anyone has signed up — an empty portal shows nothing about what the portal is
 * for. Every real account starts empty and fills up from the student's own
 * actions; this one is the showroom.
 *
 *   student@glovels.com / glovels123
 *
 * Delete `data/` and restart to get it back exactly as it was.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DEMO_EMAIL = 'student@glovels.com';
const DEMO_PASSWORD = 'glovels123';

/* The other two sides of the same conversation. A chat screen with nobody on
   the other end is a form, so the demo ships with a counsellor who can actually
   answer and an admin who can assign them. */
const COUNSELLOR = { email: 'kavya@glovels.com', password: 'glovels123', name: 'Kavya Menon', phone: '+919000000001' };
const ADMIN      = { email: 'admin@glovels.com', password: 'glovels123', name: 'Glovels Admin', phone: '+919000000002' };

/* A real, openable PDF, built here rather than shipped as a binary blob. The
   documents screen offers these for download, and a file that will not open is
   a worse demo than no file at all. */
function placeholderPdf(title) {
  const text = `(${title.replace(/[()\\]/g, '')}) Tj`;
  const objs = [
    '<</Type/Catalog/Pages 2 0 R>>',
    '<</Type/Pages/Kids[3 0 R]/Count 1>>',
    '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>',
    null,   // filled below: the content stream
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
  ];
  const stream = `BT /F1 16 Tf 60 780 Td ${text} ET\n`
    + 'BT /F1 11 Tf 60 750 Td (Placeholder document generated by the Glovels demo server.) Tj ET\n'
    + 'BT /F1 11 Tf 60 732 Td (Replace it by uploading the real file on the Documents screen.) Tj ET';
  objs[3] = `<</Length ${stream.length}>>\nstream\n${stream}\nendstream`;

  let out = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`
    + offsets.map(o => String(o).padStart(10, '0') + ' 00000 n \n').join('');
  out += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
}

const PROFILE = {
  fullName: 'Vishal Sakhamuri', dob: '2002-04-11', gender: 'Male', city: 'Hyderabad',
  phone: '98765 43210', email: DEMO_EMAIL,
  x_board: 'CBSE', x_year: '2018', x_score: '88%', x_school: 'Delhi Public School',
  xii_board: 'CBSE', xii_year: '2020', xii_score: '91%', xii_stream: 'Science (PCM)',
  d_uni: 'JNTU Hyderabad', d_course: 'B.Tech Electronics & Communication', d_dur: '4 years',
  d_year: '2024', d_cgpa: '7.6', d_backlog: 'None',
  e_test: 'IELTS', e_score: '7.0', e_date: '2026-03-14', e_low: '6.5',
  a_test: 'Not required',
  w_has: 'Yes — internship', w_emp: 'Qualcomm India', w_role: 'Intern, Embedded Systems', w_months: '6',
  g_level: "Master's", g_field: 'Data Science', g_country: 'Germany', g_intake: 'Winter 2026',
  g_why: 'I built a fault-detection model for my final-year project and want to take it further '
       + 'where the research and the industry sit close together.',
  b_total: 'Under ₹10 Lakhs', b_fund: 'A mix', b_loan: 'Yes', b_spons: 'Parent',
  r1_name: 'Prof. S. Raghavan', r1_role: 'Head of Department, ECE', r1_mail: 'raghavan@jntuh.ac.in',
  p_has: 'Yes', p_num: 'M4471902', p_exp: '2031-08-02', p_refuse: 'No',
};

const DOCS = [
  ['passport', 'passport-front-back.pdf', 'Passport', 'ok'],
  ['x', 'class10-marksheet.pdf', 'Class 10 marksheet', 'ok'],
  ['xii', 'class12-marksheet.pdf', 'Class 12 marksheet', 'ok'],
  ['degree', 'btech-transcripts.pdf', 'Degree transcripts', 'wait'],
  ['english', 'ielts-trf.pdf', 'IELTS test report form', 'wait'],
  ['photo', 'passport-photo.pdf', 'Passport photograph', 'ok'],
];

/* Stage per application, so the trackers, the counters and the deadline badges
   all have something to show. The first one carries an offer. */
const APP_STAGES = [[4, 'offer'], [3, ''], [2, ''], [2, ''], [1, ''], [0, '']];

/* The catalogue starts as the 153 programmes the site was built with, then
   lives in the database. Seeded separately from the demo accounts, because a
   real deployment wants the catalogue and not the demo student. */
/*
 * Three programme names shipped with `&amp;` written into them — double-escaped
 * when the site was first generated — and rendered on the home page as the
 * literal text "AI &amp; Machine Learning". Decoding on the way in fixes the
 * seed; this repairs a database that already has them, once, on start-up.
 *
 * It only touches a value that actually changes when decoded, so it is a no-op
 * on every later boot and cannot mangle a name that legitimately contains an
 * ampersand.
 */
function repairEntities(db) {
  const decode = decodeEntities;
  let n = 0;
  db.programmes(true).forEach(r => {
    const fixed = {
      program: decode(r.program), university: decode(r.university),
      city: decode(r.city), field: decode(r.field),
    };
    if (fixed.program === r.program && fixed.university === r.university
        && fixed.city === (r.city || '') && fixed.field === (r.field || '')) return;
    db.saveProgramme({
      id: r.id, program: fixed.program, university: fixed.university,
      city: fixed.city, country: r.country, level: r.level, field: fixed.field,
      band: r.band, isPublic: !!r.is_public, fit: r.fit, totalInr: r.total_inr,
      url: r.url, active: !!r.active, featured: !!r.featured,
      featureSort: r.feature_sort || 0,
      intakes: (() => { try { return JSON.parse(r.intakes); } catch (e) { return []; } })(),
    }, 'entity repair');
    n++;
  });
  if (n) db.log('system', 'programme names repaired', n + ' had &amp; written into them');
  return n;
}

const decodeEntities = s => String(s == null ? '' : s)
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');

function seedCatalogue({ db, catalogue, countries }) {
  if (db.programmes(true).length) return repairEntities(db) ? 0 : 0;
  /* The entry requirements come in with the destination. Everything that is
     not code/name/flag/region is a fact the finder's Requirements panel shows,
     and it is seeded here so the office can edit it from day one rather than
     finding an empty form. */
  const FACT_KEYS = ['minCgpaPublic', 'minCgpaPrivate', 'degreeRule', 'backlogRule',
    'extraNote', 'tests', 'fundsLabel', 'fundsInr', 'fundsNote', 'livingInr',
    'workRights', 'deadlineNote', 'documents', 'hasPublicTrack', 'tuitionFree'];
  Object.values(countries || {}).forEach((c, i) => {
    const facts = {};
    FACT_KEYS.forEach(k => { if (c[k] !== undefined) facts[k] = c[k]; });
    db.saveCountry({
      code: c.code, name: c.name, flag: c.flag, region: c.region || '',
      sort: i * 10, facts,
    });
  });
  /* Decoded on the way in, not repaired afterwards. catalogue.json is
     regenerated by build_portal.py from the page, which carries the
     double-escaped names — so fixing the file is undone by the next build, and
     the only durable place is here, where every import passes through. */
  catalogue.forEach(p => db.saveProgramme(Object.assign({}, p, {
    program: decodeEntities(p.program),
    university: decodeEntities(p.university),
    city: decodeEntities(p.city),
    field: decodeEntities(p.field),
  }), 'initial import'));
  db.log('system', 'catalogue imported',
    catalogue.length + ' programmes, ' + Object.keys(countries || {}).length + ' destinations');
  return catalogue.length;
}

/*
 * The six posts that were already on the site, brought in as drafts.
 *
 * They are static HTML files carrying a headline, a lead paragraph and a note
 * to ourselves where the article should be. Read once, on a database that has
 * no posts yet, so the blog screen opens on six half-written posts to finish
 * rather than on an empty list — and so the titles and descriptions somebody
 * wrote for search do not have to be typed again.
 *
 * Drafts, every one. None of them has a body, and a published post with no
 * words is a headline with a URL on it.
 */
function seedPosts({ db, root }) {
  if (db.allPosts().length) return 0;
  const dir = path.join(root, 'post');
  let files = [];
  try { files = fs.readdirSync(dir).filter(f => f.endsWith('.html') && !f.startsWith('_')); }
  catch (e) { return 0; }

  const pick = (html, re) => { const m = re.exec(html); return m ? m[1] : ''; };
  const unent = s => decodeEntities(String(s || '')).replace(/\s+/g, ' ').trim();
  let n = 0;

  for (const f of files.sort()) {
    let html;
    try { html = fs.readFileSync(path.join(dir, f), 'utf8'); } catch (e) { continue; }
    const slug = f.slice(0, -5);
    const title = unent(pick(html, /<h1>([\s\S]*?)<\/h1>/))
      || unent(pick(html, /<title>([\s\S]*?)(?: \| Glovels)?<\/title>/));
    if (!title) continue;
    const desc = unent(pick(html, /<meta name="description" content="([^"]*)"/));
    const lead = unent(pick(html, /<p class="lead">([\s\S]*?)<\/p>/));
    /* The dateline reads "2026-07-16 &middot; 7 min". Only the date is worth
       keeping — the reading time is computed from the words once there are
       any. */
    const when = pick(html, /<h1>[\s\S]*?<\/h1><p>(\d{4}-\d{2}-\d{2})/);

    db.addPost({
      slug, title,
      excerpt: lead || desc,
      body: '',
      status: 'draft',
      metaTitle: '',
      metaDesc: desc,
      keywords: '',
      author: '',
      createdAt: when ? when + 'T09:00:00.000Z' : undefined,
      updatedBy: 'imported from the site',
    });
    n++;
  }
  if (n) db.log('system', 'blog imported', n + ' posts from the pages already on the site');
  return n;
}

/*
 * Two numbers that stopped making sense when the results grew tabs.
 *
 * A visitor who has typed nothing sees a sample of the catalogue. It used to
 * be one mixed column — three public rows and two private ones, five rows,
 * fine. Then private and public were split into their own tabs, and the tab
 * that opens by default opens on two rows: not a sample, a shrug. The list
 * scrolls, so the rest cost nothing to show.
 *
 * The shipped defaults are changed in content.json, which fixes it for a
 * database that has never had the Finder screen saved. This is for the ones
 * that have: it corrects the pair ONLY if it is still exactly the pair we
 * shipped, and it runs once, so an office that deliberately sets three and two
 * tomorrow keeps them.
 */
function bumpBrowseCaps({ db, content }) {
  if (db.content('finderCapsV2')) return false;
  db.setContent('finderCapsV2', { done: true }, 'system');
  const f = db.content('finder');
  if (!f || typeof f !== 'object') return false;
  if (Number(f.browsePublic) !== 3 || Number(f.browsePrivate) !== 2) return false;
  const next = Object.assign({}, f, { browsePublic: 12, browsePrivate: 24 });
  db.setContent('finder', next, 'system');
  db.log('system', 'browse sample widened',
    'the results split into two tabs, and the private tab opened on two rows');
  return true;
}

/*
 * Services shipped since this database was seeded.
 *
 * content.json is read once, on the first run. After that the database is the
 * truth — which is right, because the office edits these from the Home page
 * screen and a redeploy must not undo that. The cost is that a service added
 * to the shipped list after a deployment exists nowhere on that deployment,
 * and there is no message anywhere saying so.
 *
 * This adds only the ids the database has never seen, and never touches one it
 * already has: a price the office changed, a description they rewrote, or a
 * service they deliberately hid all survive. New arrivals come in hidden —
 * `active: false` — because a service on the site with a price of "on request"
 * and nobody briefed to answer is worse than one that is not there yet. The
 * office turns each on when it is ready to sell.
 */
function addMissingServices({ db, content }) {
  const shipped = (content && content.services && content.services.items) || [];
  if (!shipped.length) return 0;
  const live = db.content('services');
  if (!live || !Array.isArray(live.items)) return 0;   /* first run seeds it whole */

  /* Two things have to be true before a service is added: the database has
     never had it, AND we have never offered it before.
     
     The second half matters more than it looks. Without it, a service the
     office deliberately deleted comes back on the next deploy, hidden, and
     comes back again on the one after that — for ever, because "not in the
     database" is exactly what deleting it achieved. The record of what has
     been offered is what tells those two states apart. */
  const offered = new Set(((db.content('servicesOffered') || {}).ids) || []);
  const have = new Set(live.items.map(x => String(x.id)));
  const fresh = shipped
    .filter(x => !have.has(String(x.id)) && !offered.has(String(x.id)))
    .map(x => Object.assign({}, x, { active: false }));

  /* Written whether or not anything was added, so the first run after this
     ships does not treat every existing service as new next time. */
  db.setContent('servicesOffered',
    { ids: shipped.map(x => String(x.id)) }, 'system');
  if (!fresh.length) return 0;

  /* Tabs too, or a service in a new category is in the database and on no
     screen — the chips are markup and the grid filters by them. */
  const tabs = (live.tabs || []).slice();
  const tabKeys = new Set(tabs.map(t => String(t.key)));
  ((content.services.tabs) || []).forEach(t => {
    if (!tabKeys.has(String(t.key))) tabs.push(t);
  });

  db.setContent('services', { tabs, items: live.items.concat(fresh) }, 'system');
  db.log('system', 'new services available',
    fresh.length + ' added, hidden until the office turns them on: '
    + fresh.map(x => x.name).join(', '));
  return fresh.length;
}

/*
 * The ten services that arrived switched off.
 *
 * addMissingServices brings a newly-shipped service to an existing deployment
 * hidden, on the reasoning that a service on the site with nobody briefed to
 * sell it is worse than one that is not there yet. Right in general; wrong for
 * these ten, which carry no price at all — they say "Price on request" and the
 * only button on them asks a counsellor. There is nothing to be briefed on and
 * nothing to get wrong, and an enquiry is the point.
 *
 * One-shot, and only for services that are still exactly as they shipped: no
 * price, and never edited. An office that deliberately hides one of them
 * tomorrow keeps it hidden, because this never runs again.
 */
/*
 * The three ways in under ₹5,000, on a database that was seeded before they
 * existed.
 *
 * Same rule as the services above, and the same reason: content.json is read
 * once, on the first run, and after that the database is the truth because the
 * office edits these prices. So a package shipped later exists nowhere on a
 * running deployment — and this one is not a nice-to-have, it is the whole
 * bottom of the price ladder.
 *
 * Unlike a new service, these go on VISIBLE. A hidden ₹99 card is the same as
 * no ₹99 card, there is no price to get wrong (it is written here), and nobody
 * needs briefing to sell it — that is the point of a tier the machine
 * delivers. The `entryTiers` flag records that they have been offered, so a
 * package the office deliberately deletes stays deleted.
 */
function addEntryTiers({ db, content }) {
  const shipped = ((content && content.packages && content.packages.items) || [])
    .filter(p => Number(p.matches || 0) > 0);
  if (!shipped.length) return 0;
  const live = db.content('packages');
  if (!live || !Array.isArray(live.items)) return 0;   /* first run seeds it whole */

  const offered = new Set(((db.content('entryTiers') || {}).ids) || []);
  const have = new Set(live.items.map(x => String(x.id)));
  const fresh = shipped.filter(x => !have.has(String(x.id)) && !offered.has(String(x.id)));

  /* Written whether or not anything was added, so this never runs twice over
     the same package. */
  db.setContent('entryTiers', { ids: shipped.map(x => String(x.id)) }, 'system');
  if (!fresh.length) return 0;

  /* In front of everything they undercut. `sort` is renumbered per tab by the
     content layer, so what matters here is the order of the array. */
  const items = fresh.concat(live.items);
  db.setContent('packages', Object.assign({}, live, { items }), 'system');
  db.log('system', 'entry packages added',
    fresh.map(x => x.title + ' (₹' + x.priceInr + ')').join(', ')
    + ' — delivered by the matcher, no counsellor in the loop');
  return fresh.length;
}

function openOnRequestServices({ db }) {
  if (db.content('servicesOnRequestV1')) return 0;
  db.setContent('servicesOnRequestV1', { done: true }, 'system');

  const live = db.content('services');
  if (!live || !Array.isArray(live.items)) return 0;

  let n = 0;
  const items = live.items.map(x => {
    const untouched = x.active === false
      && !Number(x.priceInr)
      && !x.isFree
      && /on request/i.test(String(x.priceLabel || ''));
    if (!untouched) return x;
    n++;
    return Object.assign({}, x, { active: true });
  });
  if (!n) return 0;

  db.setContent('services', { tabs: live.tabs, items }, 'system');
  db.log('system', 'services opened',
    n + ' priced on request \u2014 the button asks a counsellor');
  return n;
}

/*
 * The six posts, written into the drafts that were waiting for them.
 *
 * seedPosts imported the titles off the shipped pages as empty drafts, and
 * would not run again once any post existed — so a body written later reached a
 * fresh database and nowhere else. This fills a draft whose body is STILL
 * EMPTY, and touches nothing else.
 *
 * Never overwrites. A post the office has started writing has a body, and a
 * body means hands off, whatever we shipped. A post they published is left
 * alone for the same reason.
 *
 * They arrive as drafts, not published. The words are ours to supply; the
 * decision to put them on the site belongs to the person whose name is at the
 * bottom of it.
 */
function fillEmptyPosts({ db, root }) {
  let shipped = [];
  try {
    shipped = JSON.parse(fs.readFileSync(path.join(root, 'posts.json'), 'utf8'));
  } catch (e) { return 0; }
  if (!Array.isArray(shipped) || !shipped.length) return 0;

  const have = db.allPosts();
  let n = 0;

  for (const s of shipped) {
    const row = have.find(x => x.slug === s.slug);
    if (!row) continue;
    if (String(row.body || '').trim()) continue;      /* somebody has written */

    db.updatePost(row.id, {
      slug: row.slug,
      title: s.title || row.title,
      excerpt: s.excerpt || row.excerpt || '',
      body: s.body || '',
      cover: row.cover || '',
      author: row.author || '',
      tag: row.tag || '',
      status: 'draft',
      metaTitle: row.meta_title || '',
      metaDesc: s.metaDescription || row.meta_desc || '',
      keywords: row.keywords || '',
      ogImage: row.og_image || '',
      readMins: Math.max(1, Math.round(String(s.body || '').split(/\s+/).length / 200)),
      publishedAt: row.published_at || '',
      updatedBy: 'system',
    });
    n++;
  }

  if (n) {
    db.log('system', 'blog posts written',
      n + ' draft(s) filled in \u2014 read them and press Publish');
  }
  return n;
}

function run({ db, uploadDir, catalogue, hashPassword, newSalt, password }) {
  if (db.studentByEmail(DEMO_EMAIL)) return null;
  /* A shared test link overrides this, so the three demo accounts are not
     sitting on the internet behind a password anyone can read in the README. */
  const PW = password || DEMO_PASSWORD;

  const csalt = newSalt();
  const counsellor = db.createStudent(COUNSELLOR.email, COUNSELLOR.name, COUNSELLOR.phone,
    hashPassword(PW, csalt), csalt, 'counsellor');

  const asalt = newSalt();
  db.createStudent(ADMIN.email, ADMIN.name, ADMIN.phone,
    hashPassword(PW, asalt), asalt, 'admin');

  const salt = newSalt();
  const s = db.createStudent(DEMO_EMAIL, 'Vishal Sakhamuri', '+919876543210',
    hashPassword(PW, salt), salt);
  db.assignCounsellor(s.id, counsellor.id);

  db.putProfile(s.id, PROFILE);

  /* Five public programmes and two private ones — the same shape the sales page
     hands over after a purchase, so the demo account and a real one differ only
     in how they got there. */
  const pub = catalogue.filter(p => p.isPublic).slice(0, 5);
  const priv = catalogue.filter(p => !p.isPublic).slice(0, 2);
  const chosen = pub.concat(priv);
  /* The office's list — the same shape a purchase hands over. The last two go
     in as the student's own interest, so the demo account shows both lists
     rather than an empty one and a full one. */
  chosen.forEach((p, i) => db.addShortlist(s.id, p, i >= chosen.length - 2 ? 'student' : 'office'));

  chosen.forEach((p, i) => {
    const st = APP_STAGES[i];
    if (st) db.putApplication(s.id, p.id, st[0], st[1]);
  });

  const dir = path.join(uploadDir, String(s.id));
  fs.mkdirSync(dir, { recursive: true });
  DOCS.forEach(([key, filename, title, status]) => {
    const stored = key + '-demo.pdf';
    const buf = placeholderPdf(title);
    fs.writeFileSync(path.join(dir, stored), buf);
    db.addDocument(s.id, key, filename, stored, buf.length);
    if (status === 'ok') db.setDocStatus(s.id, key, 'ok');
  });

  ['daad-study', 'jnmf'].forEach(id => db.saveScholarship(s.id, id));

  db.addOrder({
    studentId: s.id, reference: 'GLV-' + crypto.randomInt(1000, 9999),
    package: 'Roadmap', publicUnis: 5, grossPaise: 999900,
    name: 'Vishal Sakhamuri', email: DEMO_EMAIL, phone: '+919876543210', status: 'paid',
  });

  /* The opening two messages, from the counsellor who is now actually assigned. */
  db.addMessage(s.id, 'them',
    'Hi! I am Kavya, your counsellor for the Germany desk. I have your profile open. '
    + 'Once your documents are verified I will confirm the shortlist with you on a call.', '');
  db.addMessage(s.id, 'them',
    'Two things worth starting now, because they are the slowest: the APS certificate '
    + '(6\u20138 weeks) and your blocked account. Everything else can follow.', '');

  return {
    email: DEMO_EMAIL, password: PW, shortlisted: chosen.length,
    counsellor: COUNSELLOR.email, admin: ADMIN.email, password_all: PW,
  };
}

/*
 * The first real account, for a deployment that must not have demo logins.
 * Created once from ADMIN_EMAIL / ADMIN_PASSWORD; after that the environment
 * variables are only a way back in if the password is lost, and changing them
 * does NOT silently reset a live account's password.
 */
/**
 * The administrator account, and the way back in when its password is lost.
 *
 * ADMIN_PASSWORD creates the account and then, deliberately, stops mattering:
 * a server that silently reset the administrator's password on every restart
 * would mean anyone who can edit an environment variable owns every student
 * file, and it would undo a password changed from inside the application.
 *
 * But that leaves one situation with no way out. The password is generated by
 * the host, shown once in a dashboard, and if it is lost or mistyped there is
 * no second administrator to reset it and no route in. Deleting the disk is
 * not an answer once there are real students on it.
 *
 * So there is a switch: set ADMIN_RESET=true and the existing account's
 * password is set to ADMIN_PASSWORD on the next start, and every session it
 * has open is dropped. It is loud in the log and it is meant to be turned off
 * again immediately — a server left running with it on resets the password on
 * every deploy, which is a foothold rather than a feature.
 */
function seedAdmin({ db, admin, hashPassword, newSalt, reset }) {
  if (!admin || !admin.email || !admin.password) return null;

  const existing = db.studentByEmail(admin.email);
  if (existing) {
    if (!reset) return { existed: true, email: admin.email };

    const salt = newSalt();
    db.setPassword(existing.id, hashPassword(admin.password, salt), salt);
    /* An account that was demoted, or was never an administrator, is put back
       — otherwise the reset lets you in to a screen you cannot use. */
    if (existing.role !== 'admin') db.setRole(existing.id, 'admin');
    db.log('system', 'admin password reset from the environment', admin.email);
    return { reset: true, email: admin.email };
  }

  const salt = newSalt();
  db.createStudent(admin.email, admin.name || 'Glovels Admin', '',
    hashPassword(admin.password, salt), salt, 'admin');
  db.log('system', 'admin account created', admin.email);
  return { created: true, email: admin.email };
}

module.exports = { run, seedCatalogue, seedAdmin, seedPosts, bumpBrowseCaps,
  addMissingServices,
  addEntryTiers,
  openOnRequestServices,
  fillEmptyPosts,
  DEMO_EMAIL, DEMO_PASSWORD };
