'use strict';
/**
 * The demo account.
 *
 * Created once, on the first run, so the portal has something in it before
 * anyone has signed up — an empty portal shows nothing about what the portal is
 * for. Every real account starts empty and fills up from the student's own
 * actions; this one is the showroom.
 *
 *   student@glovels.com / glovels123
 *
 * Delete `data/` and restart to get it back exactly as it was.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DEMO_EMAIL = 'student@glovels.com';
const DEMO_PASSWORD = 'glovels123';

/* The other two sides of the same conversation. A chat screen with nobody on
   the other end is a form, so the demo ships with a counsellor who can actually
   answer and an admin who can assign them. */
const COUNSELLOR = { email: 'kavya@glovels.com', password: 'glovels123', name: 'Kavya Menon', phone: '+919000000001' };
const ADMIN      = { email: 'admin@glovels.com', password: 'glovels123', name: 'Glovels Admin', phone: '+919000000002' };

/* A real, openable PDF, built here rather than shipped as a binary blob. The
   documents screen offers these for download, and a file that will not open is
   a worse demo than no file at all. */
function placeholderPdf(title) {
  const text = `(${title.replace(/[()\\]/g, '')}) Tj`;
  const objs = [
    '<</Type/Catalog/Pages 2 0 R>>',
    '<</Type/Pages/Kids[3 0 R]/Count 1>>',
    '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>',
    null,   // filled below: the content stream
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
  ];
  const stream = `BT /F1 16 Tf 60 780 Td ${text} ET\n`
    + 'BT /F1 11 Tf 60 750 Td (Placeholder document generated by the Glovels demo server.) Tj ET\n'
    + 'BT /F1 11 Tf 60 732 Td (Replace it by uploading the real file on the Documents screen.) Tj ET';
  objs[3] = `<</Length ${stream.length}>>\nstream\n${stream}\nendstream`;

  let out = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`
    + offsets.map(o => String(o).padStart(10, '0') + ' 00000 n \n').join('');
  out += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
}

const PROFILE = {
  fullName: 'Vishal Sakhamuri', dob: '2002-04-11', gender: 'Male', city: 'Hyderabad',
  phone: '98765 43210', email: DEMO_EMAIL,
  x_board: 'CBSE', x_year: '2018', x_score: '88%', x_school: 'Delhi Public School',
  xii_board: 'CBSE', xii_year: '2020', xii_score: '91%', xii_stream: 'Science (PCM)',
  d_uni: 'JNTU Hyderabad', d_course: 'B.Tech Electronics & Communication', d_dur: '4 years',
  d_year: '2024', d_cgpa: '7.6', d_backlog: 'None',
  e_test: 'IELTS', e_score: '7.0', e_date: '2026-03-14', e_low: '6.5',
  a_test: 'Not required',
  w_has: 'Yes — internship', w_emp: 'Qualcomm India', w_role: 'Intern, Embedded Systems', w_months: '6',
  g_level: "Master's", g_field: 'Data Science', g_country: 'Germany', g_intake: 'Winter 2026',
  g_why: 'I built a fault-detection model for my final-year project and want to take it further '
       + 'where the research and the industry sit close together.',
  b_total: 'Under ₹10 Lakhs', b_fund: 'A mix', b_loan: 'Yes', b_spons: 'Parent',
  r1_name: 'Prof. S. Raghavan', r1_role: 'Head of Department, ECE', r1_mail: 'raghavan@jntuh.ac.in',
  p_has: 'Yes', p_num: 'M4471902', p_exp: '2031-08-02', p_refuse: 'No',
};

const DOCS = [
  ['passport', 'passport-front-back.pdf', 'Passport', 'ok'],
  ['x', 'class10-marksheet.pdf', 'Class 10 marksheet', 'ok'],
  ['xii', 'class12-marksheet.pdf', 'Class 12 marksheet', 'ok'],
  ['degree', 'btech-transcripts.pdf', 'Degree transcripts', 'wait'],
  ['english', 'ielts-trf.pdf', 'IELTS test report form', 'wait'],
  ['photo', 'passport-photo.pdf', 'Passport photograph', 'ok'],
];

/* Stage per application, so the trackers, the counters and the deadline badges
   all have something to show. The first one carries an offer. */
const APP_STAGES = [[4, 'offer'], [3, ''], [2, ''], [2, ''], [1, ''], [0, '']];

/* The catalogue starts as the 153 programmes the site was built with, then
   lives in the database. Seeded separately from the demo accounts, because a
   real deployment wants the catalogue and not the demo student. */
function seedCatalogue({ db, catalogue, countries }) {
  if (db.programmes(true).length) return 0;
  Object.values(countries || {}).forEach((c, i) =>
    db.saveCountry({ code: c.code, name: c.name, flag: c.flag, region: c.region || '', sort: i * 10 }));
  catalogue.forEach(p => db.saveProgramme(p, 'initial import'));
  db.log('system', 'catalogue imported',
    catalogue.length + ' programmes, ' + Object.keys(countries || {}).length + ' destinations');
  return catalogue.length;
}

function run({ db, uploadDir, catalogue, hashPassword, newSalt, password }) {
  if (db.studentByEmail(DEMO_EMAIL)) return null;
  /* A shared test link overrides this, so the three demo accounts are not
     sitting on the internet behind a password anyone can read in the README. */
  const PW = password || DEMO_PASSWORD;

  const csalt = newSalt();
  const counsellor = db.createStudent(COUNSELLOR.email, COUNSELLOR.name, COUNSELLOR.phone,
    hashPassword(PW, csalt), csalt, 'counsellor');

  const asalt = newSalt();
  db.createStudent(ADMIN.email, ADMIN.name, ADMIN.phone,
    hashPassword(PW, asalt), asalt, 'admin');

  const salt = newSalt();
  const s = db.createStudent(DEMO_EMAIL, 'Vishal Sakhamuri', '+919876543210',
    hashPassword(PW, salt), salt);
  db.assignCounsellor(s.id, counsellor.id);

  db.putProfile(s.id, PROFILE);

  /* Five public programmes and two private ones — the same shape the sales page
     hands over after a purchase, so the demo account and a real one differ only
     in how they got there. */
  const pub = catalogue.filter(p => p.isPublic).slice(0, 5);
  const priv = catalogue.filter(p => !p.isPublic).slice(0, 2);
  const chosen = pub.concat(priv);
  chosen.forEach(p => db.addShortlist(s.id, p));

  chosen.forEach((p, i) => {
    const st = APP_STAGES[i];
    if (st) db.putApplication(s.id, p.id, st[0], st[1]);
  });

  const dir = path.join(uploadDir, String(s.id));
  fs.mkdirSync(dir, { recursive: true });
  DOCS.forEach(([key, filename, title, status]) => {
    const stored = key + '-demo.pdf';
    const buf = placeholderPdf(title);
    fs.writeFileSync(path.join(dir, stored), buf);
    db.addDocument(s.id, key, filename, stored, buf.length);
    if (status === 'ok') db.setDocStatus(s.id, key, 'ok');
  });

  ['daad-study', 'jnmf'].forEach(id => db.saveScholarship(s.id, id));

  db.addOrder({
    studentId: s.id, reference: 'GLV-' + crypto.randomInt(1000, 9999),
    package: 'Roadmap', publicUnis: 5, grossPaise: 999900,
    name: 'Vishal Sakhamuri', email: DEMO_EMAIL, phone: '+919876543210', status: 'paid',
  });

  /* The opening two messages, from the counsellor who is now actually assigned. */
  db.addMessage(s.id, 'them',
    'Hi! I am Kavya, your counsellor for the Germany desk. I have your profile open. '
    + 'Once your documents are verified I will confirm the shortlist with you on a call.', '');
  db.addMessage(s.id, 'them',
    'Two things worth starting now, because they are the slowest: the APS certificate '
    + '(6\u20138 weeks) and your blocked account. Everything else can follow.', '');

  return {
    email: DEMO_EMAIL, password: PW, shortlisted: chosen.length,
    counsellor: COUNSELLOR.email, admin: ADMIN.email, password_all: PW,
  };
}

/*
 * The first real account, for a deployment that must not have demo logins.
 * Created once from ADMIN_EMAIL / ADMIN_PASSWORD; after that the environment
 * variables are only a way back in if the password is lost, and changing them
 * does NOT silently reset a live account's password.
 */
function seedAdmin({ db, admin, hashPassword, newSalt }) {
  if (!admin || !admin.email || !admin.password) return null;
  if (db.studentByEmail(admin.email)) return { existed: true, email: admin.email };
  const salt = newSalt();
  db.createStudent(admin.email, admin.name || 'Glovels Admin', '',
    hashPassword(admin.password, salt), salt, 'admin');
  db.log('system', 'admin account created', admin.email);
  return { created: true, email: admin.email };
}

module.exports = { run, seedCatalogue, seedAdmin, DEMO_EMAIL, DEMO_PASSWORD };
