'use strict';
/**
 * The demo account.
 *
 * Created once, on the first run, so the portal has something in it before
 * anyone has signed up — an empty portal shows nothing about what the portal is
 * for. Every real account starts empty and fills up from the student's own
 * actions; this one is the showroom.
 *
 *   student@glovels.com / glovels123
 *
 * Delete `data/` and restart to get it back exactly as it was.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DEMO_EMAIL = 'student@glovels.com';
const DEMO_PASSWORD = 'glovels123';

/* The other two sides of the same conversation. A chat screen with nobody on
   the other end is a form, so the demo ships with a counsellor who can actually
   answer and an admin who can assign them. */
const COUNSELLOR = { email: 'kavya@glovels.com', password: 'glovels123', name: 'Kavya Menon', phone: '+919000000001' };
const ADMIN      = { email: 'admin@glovels.com', password: 'glovels123', name: 'Glovels Admin', phone: '+919000000002' };

/* A real, openable PDF, built here rather than shipped as a binary blob. The
   documents screen offers these for download, and a file that will not open is
   a worse demo than no file at all. */
function placeholderPdf(title) {
  const text = `(${title.replace(/[()\\]/g, '')}) Tj`;
  const objs = [
    '<</Type/Catalog/Pages 2 0 R>>',
    '<</Type/Pages/Kids[3 0 R]/Count 1>>',
    '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>',
    null,   // filled below: the content stream
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
  ];
  const stream = `BT /F1 16 Tf 60 780 Td ${text} ET\n`
    + 'BT /F1 11 Tf 60 750 Td (Placeholder document generated by the Glovels demo server.) Tj ET\n'
    + 'BT /F1 11 Tf 60 732 Td (Replace it by uploading the real file on the Documents screen.) Tj ET';
  objs[3] = `<</Length ${stream.length}>>\nstream\n${stream}\nendstream`;

  let out = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`
    + offsets.map(o => String(o).padStart(10, '0') + ' 00000 n \n').join('');
  out += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
}

const PROFILE = {
  firstName: 'Vishal', lastName: 'Sakhamuri', fullName: 'Vishal Sakhamuri',
  dob: '2002-04-11', gender: 'Male', pob: 'Hyderabad', city: 'Hyderabad',
  addr1: 'Plot 60, 1st Floor', state: 'Telangana', pin: '500081',
  addr_country: 'India',
  phone: '98765 43210', email: DEMO_EMAIL,
  x_board: 'CBSE', x_year: '2018', x_score: '88%', x_school: 'Delhi Public School',
  xii_board: 'CBSE', xii_year: '2020', xii_score: '91%', xii_stream: 'Science (PCM)',
  d_uni: 'JNTU Hyderabad', d_course: 'B.Tech Electronics & Communication', d_dur: '4 years',
  d_year: '2024', d_cgpa: '7.6', d_max: '10', d_pass: '4', d_backlog: 'None',
  e_test: 'IELTS', e_score: '7.0', e_date: '2026-03-14', e_low: '6.5',
  a_test: 'Not required',
  w_has: 'Yes — internship', w_emp: 'Qualcomm India', w_role: 'Intern, Embedded Systems', w_months: '6',
  g_level: "Master's", g_field: 'Data Science', g_country: 'Germany', g_intake: 'Winter 2026',
  g_why: 'I built a fault-detection model for my final-year project and want to take it further '
       + 'where the research and the industry sit close together.',
  b_total: 'Under ₹10 Lakhs', b_fund: 'A mix', b_loan: 'Yes', b_spons: 'Parent',
  r1_name: 'Prof. S. Raghavan', r1_role: 'Head of Department, ECE', r1_mail: 'raghavan@jntuh.ac.in',
  p_has: 'Yes', p_num: 'M4471902', p_exp: '2031-08-02', p_refuse: 'No',
};

const DOCS = [
  ['passport', 'passport-front-back.pdf', 'Passport', 'ok'],
  ['x', 'class10-marksheet.pdf', 'Class 10 marksheet', 'ok'],
  ['xii', 'class12-marksheet.pdf', 'Class 12 marksheet', 'ok'],
  ['degree', 'btech-transcripts.pdf', 'Degree transcripts', 'wait'],
  ['english', 'ielts-trf.pdf', 'IELTS test report form', 'wait'],
  ['photo', 'passport-photo.pdf', 'Passport photograph', 'ok'],
];

/* Stage per application, so the trackers, the counters and the deadline badges
   all have something to show. The first one carries an offer. */
const APP_STAGES = [[4, 'offer'], [3, ''], [2, ''], [2, ''], [1, ''], [0, '']];

/* The catalogue starts as the 153 programmes the site was built with, then
   lives in the database. Seeded separately from the demo accounts, because a
   real deployment wants the catalogue and not the demo student. */
/*
 * Three programme names shipped with `&amp;` written into them — double-escaped
 * when the site was first generated — and rendered on the home page as the
 * literal text "AI &amp; Machine Learning". Decoding on the way in fixes the
 * seed; this repairs a database that already has them, once, on start-up.
 *
 * It only touches a value that actually changes when decoded, so it is a no-op
 * on every later boot and cannot mangle a name that legitimately contains an
 * ampersand.
 */
function repairEntities(db) {
  const decode = decodeEntities;
  let n = 0;
  db.programmes(true).forEach(r => {
    const fixed = {
      program: decode(r.program), university: decode(r.university),
      city: decode(r.city), field: decode(r.field),
    };
    if (fixed.program === r.program && fixed.university === r.university
        && fixed.city === (r.city || '') && fixed.field === (r.field || '')) return;
    db.saveProgramme({
      id: r.id, program: fixed.program, university: fixed.university,
      city: fixed.city, country: r.country, level: r.level, field: fixed.field,
      band: r.band, isPublic: !!r.is_public, fit: r.fit, minCgpa: r.min_cgpa,
      totalInr: r.total_inr,
      url: r.url, active: !!r.active, featured: !!r.featured,
      featureSort: r.feature_sort || 0,
      intakes: (() => { try { return JSON.parse(r.intakes); } catch (e) { return []; } })(),
    }, 'entity repair');
    n++;
  });
  if (n) db.log('system', 'programme names repaired', n + ' had &amp; written into them');
  return n;
}

const decodeEntities = s => String(s == null ? '' : s)
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');

function seedCatalogue({ db, catalogue, countries }) {
  if (db.programmes(true).length) return repairEntities(db) ? 0 : 0;
  /* The entry requirements come in with the destination. Everything that is
     not code/name/flag/region is a fact the finder's Requirements panel shows,
     and it is seeded here so the office can edit it from day one rather than
     finding an empty form. */
  const FACT_KEYS = ['minCgpaPublic', 'minCgpaPrivate', 'degreeRule', 'backlogRule',
    'extraNote', 'tests', 'fundsLabel', 'fundsInr', 'fundsNote', 'livingInr',
    'workRights', 'deadlineNote', 'documents', 'hasPublicTrack', 'tuitionFree'];
  Object.values(countries || {}).forEach((c, i) => {
    const facts = {};
    FACT_KEYS.forEach(k => { if (c[k] !== undefined) facts[k] = c[k]; });
    db.saveCountry({
      code: c.code, name: c.name, flag: c.flag, region: c.region || '',
      sort: i * 10, facts,
    });
  });
  /* Decoded on the way in, not repaired afterwards. catalogue.json is
     regenerated by build_portal.py from the page, which carries the
     double-escaped names — so fixing the file is undone by the next build, and
     the only durable place is here, where every import passes through. */
  catalogue.forEach(p => db.saveProgramme(Object.assign({}, p, {
    program: decodeEntities(p.program),
    university: decodeEntities(p.university),
    city: decodeEntities(p.city),
    field: decodeEntities(p.field),
  }), 'initial import'));
  db.log('system', 'catalogue imported',
    catalogue.length + ' programmes, ' + Object.keys(countries || {}).length + ' destinations');
  return catalogue.length;
}

/*
 * The six posts that were already on the site, brought in as drafts.
 *
 * They are static HTML files carrying a headline, a lead paragraph and a note
 * to ourselves where the article should be. Read once, on a database that has
 * no posts yet, so the blog screen opens on six half-written posts to finish
 * rather than on an empty list — and so the titles and descriptions somebody
 * wrote for search do not have to be typed again.
 *
 * Drafts, every one. None of them has a body, and a published post with no
 * words is a headline with a URL on it.
 */
function seedPosts({ db, root }) {
  if (db.allPosts().length) return 0;
  const dir = path.join(root, 'post');
  let files = [];
  try { files = fs.readdirSync(dir).filter(f => f.endsWith('.html') && !f.startsWith('_')); }
  catch (e) { return 0; }

  const pick = (html, re) => { const m = re.exec(html); return m ? m[1] : ''; };
  const unent = s => decodeEntities(String(s || '')).replace(/\s+/g, ' ').trim();
  let n = 0;

  for (const f of files.sort()) {
    let html;
    try { html = fs.readFileSync(path.join(dir, f), 'utf8'); } catch (e) { continue; }
    const slug = f.slice(0, -5);
    const title = unent(pick(html, /<h1>([\s\S]*?)<\/h1>/))
      || unent(pick(html, /<title>([\s\S]*?)(?: \| Glovels)?<\/title>/));
    if (!title) continue;
    const desc = unent(pick(html, /<meta name="description" content="([^"]*)"/));
    const lead = unent(pick(html, /<p class="lead">([\s\S]*?)<\/p>/));
    /* The dateline reads "2026-07-16 &middot; 7 min". Only the date is worth
       keeping — the reading time is computed from the words once there are
       any. */
    const when = pick(html, /<h1>[\s\S]*?<\/h1><p>(\d{4}-\d{2}-\d{2})/);

    db.addPost({
      slug, title,
      excerpt: lead || desc,
      body: '',
      status: 'draft',
      metaTitle: '',
      metaDesc: desc,
      keywords: '',
      author: '',
      createdAt: when ? when + 'T09:00:00.000Z' : undefined,
      updatedBy: 'imported from the site',
    });
    n++;
  }
  if (n) db.log('system', 'blog imported', n + ' posts from the pages already on the site');
  return n;
}

/*
 * Two numbers that stopped making sense when the results grew tabs.
 *
 * A visitor who has typed nothing sees a sample of the catalogue. It used to
 * be one mixed column — three public rows and two private ones, five rows,
 * fine. Then private and public were split into their own tabs, and the tab
 * that opens by default opens on two rows: not a sample, a shrug. The list
 * scrolls, so the rest cost nothing to show.
 *
 * The shipped defaults are changed in content.json, which fixes it for a
 * database that has never had the Finder screen saved. This is for the ones
 * that have: it corrects the pair ONLY if it is still exactly the pair we
 * shipped, and it runs once, so an office that deliberately sets three and two
 * tomorrow keeps them.
 */
function bumpBrowseCaps({ db, content }) {
  if (db.content('finderCapsV2')) return false;
  db.setContent('finderCapsV2', { done: true }, 'system');
  const f = db.content('finder');
  if (!f || typeof f !== 'object') return false;
  if (Number(f.browsePublic) !== 3 || Number(f.browsePrivate) !== 2) return false;
  const next = Object.assign({}, f, { browsePublic: 12, browsePrivate: 24 });
  db.setContent('finder', next, 'system');
  db.log('system', 'browse sample widened',
    'the results split into two tabs, and the private tab opened on two rows');
  return true;
}

/*
 * Services shipped since this database was seeded.
 *
 * content.json is read once, on the first run. After that the database is the
 * truth — which is right, because the office edits these from the Home page
 * screen and a redeploy must not undo that. The cost is that a service added
 * to the shipped list after a deployment exists nowhere on that deployment,
 * and there is no message anywhere saying so.
 *
 * This adds only the ids the database has never seen, and never touches one it
 * already has: a price the office changed, a description they rewrote, or a
 * service they deliberately hid all survive. New arrivals come in hidden —
 * `active: false` — because a service on the site with a price of "on request"
 * and nobody briefed to answer is worse than one that is not there yet. The
 * office turns each on when it is ready to sell.
 */
function addMissingServices({ db, content }) {
  const shipped = (content && content.services && content.services.items) || [];
  if (!shipped.length) return 0;
  const live = db.content('services');
  if (!live || !Array.isArray(live.items)) return 0;   /* first run seeds it whole */

  /* Two things have to be true before a service is added: the database has
     never had it, AND we have never offered it before.
     
     The second half matters more than it looks. Without it, a service the
     office deliberately deleted comes back on the next deploy, hidden, and
     comes back again on the one after that — for ever, because "not in the
     database" is exactly what deleting it achieved. The record of what has
     been offered is what tells those two states apart. */
  const offered = new Set(((db.content('servicesOffered') || {}).ids) || []);
  const have = new Set(live.items.map(x => String(x.id)));
  const fresh = shipped
    .filter(x => !have.has(String(x.id)) && !offered.has(String(x.id)))
    .map(x => Object.assign({}, x, { active: false }));

  /* Written whether or not anything was added, so the first run after this
     ships does not treat every existing service as new next time. */
  db.setContent('servicesOffered',
    { ids: shipped.map(x => String(x.id)) }, 'system');
  if (!fresh.length) return 0;

  /* Tabs too, or a service in a new category is in the database and on no
     screen — the chips are markup and the grid filters by them. */
  const tabs = (live.tabs || []).slice();
  const tabKeys = new Set(tabs.map(t => String(t.key)));
  ((content.services.tabs) || []).forEach(t => {
    if (!tabKeys.has(String(t.key))) tabs.push(t);
  });

  db.setContent('services', { tabs, items: live.items.concat(fresh) }, 'system');
  db.log('system', 'new services available',
    fresh.length + ' added, hidden until the office turns them on: '
    + fresh.map(x => x.name).join(', '));
  return fresh.length;
}

/*
 * The ten services that arrived switched off.
 *
 * addMissingServices brings a newly-shipped service to an existing deployment
 * hidden, on the reasoning that a service on the site with nobody briefed to
 * sell it is worse than one that is not there yet. Right in general; wrong for
 * these ten, which carry no price at all — they say "Price on request" and the
 * only button on them asks a counsellor. There is nothing to be briefed on and
 * nothing to get wrong, and an enquiry is the point.
 *
 * One-shot, and only for services that are still exactly as they shipped: no
 * price, and never edited. An office that deliberately hides one of them
 * tomorrow keeps it hidden, because this never runs again.
 */
/*
 * The three ways in under ₹5,000, on a database that was seeded before they
 * existed.
 *
 * Same rule as the services above, and the same reason: content.json is read
 * once, on the first run, and after that the database is the truth because the
 * office edits these prices. So a package shipped later exists nowhere on a
 * running deployment — and this one is not a nice-to-have, it is the whole
 * bottom of the price ladder.
 *
 * Unlike a new service, these go on VISIBLE. A hidden ₹99 card is the same as
 * no ₹99 card, there is no price to get wrong (it is written here), and nobody
 * needs briefing to sell it — that is the point of a tier the machine
 * delivers. The `entryTiers` flag records that they have been offered, so a
 * package the office deliberately deletes stays deleted.
 */
function addEntryTiers({ db, content }) {
  const shipped = ((content && content.packages && content.packages.items) || [])
    .filter(p => Number(p.matches || 0) > 0);
  if (!shipped.length) return 0;
  const live = db.content('packages');
  if (!live || !Array.isArray(live.items)) return 0;   /* first run seeds it whole */

  const offered = new Set(((db.content('entryTiers') || {}).ids) || []);
  const have = new Set(live.items.map(x => String(x.id)));
  const fresh = shipped.filter(x => !have.has(String(x.id)) && !offered.has(String(x.id)));

  /* Written whether or not anything was added, so this never runs twice over
     the same package. */
  db.setContent('entryTiers', { ids: shipped.map(x => String(x.id)) }, 'system');
  if (!fresh.length) return 0;

  /* In front of everything they undercut. `sort` is renumbered per tab by the
     content layer, so what matters here is the order of the array. */
  const items = fresh.concat(live.items);
  db.setContent('packages', Object.assign({}, live, { items }), 'system');
  db.log('system', 'entry packages added',
    fresh.map(x => x.title + ' (₹' + x.priceInr + ')').join(', ')
    + ' — delivered by the matcher, no counsellor in the loop');
  return fresh.length;
}

/*
 * The two that turned out to be services, not packages.
 *
 * ₹99 and ₹999 shipped in the packages block one deploy ago and are moving to
 * the services grid, because the packages section is headed "Public University
 * Admission" and both of them deliver PRIVATE universities. A card that reads
 * "3 private universities" under a tab that says public is the section
 * contradicting itself.
 *
 * On a database seeded before that decision they exist as packages, and no
 * amount of shipping the right content.json moves them — the database is the
 * truth for these blocks, deliberately, because the office edits them. So they
 * are taken out of the packages block by id and added to the services block
 * from the shipped list.
 *
 * The office's own edits are respected in the one way that matters here: if
 * somebody has already deleted one of these from the packages list, removing it
 * again is a no-op, and if they have already got the service, it is not added
 * twice.
 */
const MOVED_TO_SERVICES = ['pkg-first-three', 'pkg-shortlist-ten'];

function moveEntryTiersToServices({ db, content }) {
  if (db.content('entryTiersAreServices')) return 0;
  db.setContent('entryTiersAreServices', { done: true }, 'system');

  let moved = 0;

  /* Out of packages. */
  const pkgs = db.content('packages');
  if (pkgs && Array.isArray(pkgs.items)) {
    const keep = pkgs.items.filter(x => !MOVED_TO_SERVICES.includes(String(x.id)));
    if (keep.length !== pkgs.items.length) {
      moved = pkgs.items.length - keep.length;
      db.setContent('packages', Object.assign({}, pkgs, { items: keep }), 'system');
    }
  }

  /* Into services, visible, at the front. A hidden ₹99 card is the same as no
     ₹99 card — there is no price to get wrong and nobody to brief, which is
     the whole point of a tier the machine delivers. */
  const shipped = ((content && content.services && content.services.items) || [])
    .filter(x => Number(x.matches || 0) > 0);
  const live = db.content('services');
  if (shipped.length && live && Array.isArray(live.items)) {
    const have = new Set(live.items.map(x => String(x.id)));
    const fresh = shipped.filter(x => !have.has(String(x.id)));
    if (fresh.length) {
      db.setContent('services',
        Object.assign({}, live, { items: fresh.concat(live.items) }), 'system');
      /* And record them as offered, so addMissingServices does not see them as
         new arrivals and add them again, hidden. */
      const offered = new Set(((db.content('servicesOffered') || {}).ids) || []);
      fresh.forEach(x => offered.add(String(x.id)));
      db.setContent('servicesOffered', { ids: [...offered] }, 'system');
      db.log('system', 'entry tiers moved to services',
        fresh.map(x => x.name + ' (₹' + x.priceInr + ')').join(', ')
        + ' — out of the public-university packages, into the services grid');
      return fresh.length;
    }
  }
  return moved;
}

/*
 * "Full end-to-end packages run from ₹9,999 to ₹74,999."
 *
 * It is ₹4,999 now — that is the cheapest package that reveals a public
 * university name. The sentence lives in the FAQ block, which the office can
 * edit, so this only rewrites it when it is still word for word the shipped
 * one. An office that has rewritten that answer keeps their version; a number
 * nobody has touched gets corrected rather than quietly staying wrong.
 */
function fixCheapestPackagePrice({ db }) {
  if (db.content('faqCheapestV2')) return 0;
  db.setContent('faqCheapestV2', { done: true }, 'system');

  const live = db.content('faq');
  if (!Array.isArray(live)) return 0;

  const WAS = 'full end-to-end packages run from \u20b99,999 to \u20b974,999';
  const NOW = 'packages run from \u20b94,999 to \u20b974,999';
  let n = 0;
  const next = live.map(f => {
    if (!f || typeof f.a !== 'string' || !f.a.includes(WAS)) return f;
    n++;
    return Object.assign({}, f, { a: f.a.replace(WAS, NOW) });
  });
  if (!n) return 0;
  db.setContent('faq', next, 'system');
  db.log('system', 'price in the FAQ corrected',
    'the cheapest package that reveals a public university name is \u20b94,999');
  return n;
}

/*
 * The packages that unlock public universities, delivering them.
 *
 * "University shortlist for public is not shown in the student login even
 *  after paid… when paid in full we need to show list of public unis after the
 *  filter criteria. Adding or removing can be done later by counsellor."
 *
 * `unlocks` is how many public NAMES a package reveals. `matches` is how many
 * universities the machine actually puts on the student's shortlist when they
 * pay. Only the ₹4,999 tier had both. ₹9,999, ₹49,999 and ₹74,999 unlocked
 * five, ten and fifteen names with `matches` at zero — so they revealed names
 * to anybody who went and searched the finder, and put nothing on the
 * student's own screen. Somebody paying ₹74,999 signed in to an empty
 * shortlist while somebody paying ₹4,999 got three universities.
 *
 * Only fills a zero. A package where the office has deliberately set a number
 * is theirs, and a package that unlocks nothing is a work or migration tier
 * with no university list to deliver.
 */
function packagesDeliverWhatTheyUnlock({ db }) {
  if (db.content('packagesDeliverV1')) return 0;
  db.setContent('packagesDeliverV1', { done: true }, 'system');

  const live = db.content('packages');
  if (!live || !Array.isArray(live.items)) return 0;

  let n = 0;
  const names = [];
  const items = live.items.map(p => {
    const unlocks = Number(p.unlocks || p.publicUnis || 0);
    if (!unlocks || Number(p.matches || 0) > 0) return p;
    n++;
    names.push((p.title || p.id) + ' \u2192 ' + unlocks);
    return Object.assign({}, p, { matches: unlocks });
  });
  if (!n) return 0;

  db.setContent('packages', Object.assign({}, live, { items }), 'system');
  db.log('system', 'packages deliver the universities they unlock', names.join(', '));
  return n;
}

/*
 * The card that showed a visitor the code that draws the card.
 *
 * `build_content.py` finds the home page's testimonials by looking for
 * `<article class="card card-hover card-stack tcard">` and the FAQ by looking
 * for `<details class="faq"><summary>`. The JavaScript that RENDERS those two
 * blocks lives in the same page and builds that markup out of string
 * literals — so the extractor matched its own renderer, and a fourth
 * testimonial reading `' + E(t.route) + '` went into content.json, into the
 * database, and onto the live home page. The FAQ carried the same phantom.
 *
 * The extractor is fixed, but a database seeded before that keeps its copy —
 * content is seeded once and then belongs to the office. This takes the two
 * rows out, and only those two: a row qualifies only if it still contains the
 * concatenation operator and the escaper's name, which is not something
 * anybody types into a testimonial about themselves.
 */
const LOOKS_LIKE_SOURCE = v =>
  typeof v === 'string' && /\+ E\([ft]\.[a-z]+\)/.test(v);

function removeTheCardsThatWereSourceCode({ db }) {
  if (db.content('phantomCardsV1')) return 0;
  db.setContent('phantomCardsV1', { done: true }, 'system');

  let n = 0;
  for (const key of ['testimonials', 'faq']) {
    const live = db.content(key);
    if (!Array.isArray(live)) continue;
    const kept = live.filter(row =>
      !(row && typeof row === 'object' && Object.values(row).some(LOOKS_LIKE_SOURCE)));
    if (kept.length === live.length) continue;
    n += live.length - kept.length;
    db.setContent(key, kept, 'system');
    db.log('system', 'removed a ' + key + ' row that was the renderer, not content',
      (live.length - kept.length) + ' removed, ' + kept.length + ' left');
  }
  return n;
}

/*
 * The question each chip asks, on a deployment seeded before it existed.
 *
 * The studio's chips carried a label and one fixed phrase, so every student
 * who ticked "Work experience" got the words "my time working in a real team"
 * and the draft had no evidence in it at all. Each chip now asks what the work
 * actually was, and there is a paragraph for the answers.
 *
 * Content is seeded once and then belongs to the office, so an existing
 * database keeps the old block and the studio would ask "What was it,
 * exactly?" for all eight chips forever. This fills in what is MISSING and
 * nothing else: a chip that already has a question keeps it, a label or phrase
 * somebody rewrote is never touched, and the detail paragraphs are only
 * written if there are none.
 */
function chipsAskWhatItWas({ db, content }) {
  if (db.content('chipsAskV1')) return 0;
  db.setContent('chipsAskV1', { done: true }, 'system');

  const live = db.content('writing');
  const ship = (content && content.writing) || {};
  if (!live || !ship.sop) return 0;

  let n = 0;
  const next = JSON.parse(JSON.stringify(live));

  for (const kind of ['sop', 'lor']) {
    const l = next[kind], s = ship[kind];
    if (!l || !s) continue;

    const byKey = new Map((s.signals || []).map(c => [c.key, c]));
    (l.signals || []).forEach(c => {
      const from = byKey.get(c.key);
      if (!from) return;
      if (!c.ask && from.ask) { c.ask = from.ask; n++; }
      if (!c.eg && from.eg) { c.eg = from.eg; }
    });

    if (!(l.detail || []).length && (s.detail || []).length) {
      l.detail = s.detail.slice();
      n++;
    }
  }
  if (!n) return 0;

  db.setContent('writing', next, 'system');
  db.log('system', 'the studio asks what the experience actually was',
    n + ' field(s) filled in');
  return n;
}

function openOnRequestServices({ db }) {
  if (db.content('servicesOnRequestV1')) return 0;
  db.setContent('servicesOnRequestV1', { done: true }, 'system');

  const live = db.content('services');
  if (!live || !Array.isArray(live.items)) return 0;

  let n = 0;
  const items = live.items.map(x => {
    const untouched = x.active === false
      && !Number(x.priceInr)
      && !x.isFree
      && /on request/i.test(String(x.priceLabel || ''));
    if (!untouched) return x;
    n++;
    return Object.assign({}, x, { active: true });
  });
  if (!n) return 0;

  db.setContent('services', { tabs: live.tabs, items }, 'system');
  db.log('system', 'services opened',
    n + ' priced on request \u2014 the button asks a counsellor');
  return n;
}

/*
 * The six posts, written into the drafts that were waiting for them.
 *
 * seedPosts imported the titles off the shipped pages as empty drafts, and
 * would not run again once any post existed — so a body written later reached a
 * fresh database and nowhere else. This fills a draft whose body is STILL
 * EMPTY, and touches nothing else.
 *
 * Never overwrites. A post the office has started writing has a body, and a
 * body means hands off, whatever we shipped. A post they published is left
 * alone for the same reason.
 *
 * They arrive as drafts, not published. The words are ours to supply; the
 * decision to put them on the site belongs to the person whose name is at the
 * bottom of it.
 */
function fillEmptyPosts({ db, root }) {
  let shipped = [];
  try {
    shipped = JSON.parse(fs.readFileSync(path.join(root, 'posts.json'), 'utf8'));
  } catch (e) { return 0; }
  if (!Array.isArray(shipped) || !shipped.length) return 0;

  const have = db.allPosts();
  let n = 0;

  for (const s of shipped) {
    const row = have.find(x => x.slug === s.slug);
    if (!row) continue;
    if (String(row.body || '').trim()) continue;      /* somebody has written */

    db.updatePost(row.id, {
      slug: row.slug,
      title: s.title || row.title,
      excerpt: s.excerpt || row.excerpt || '',
      body: s.body || '',
      cover: row.cover || '',
      author: row.author || '',
      tag: row.tag || '',
      status: 'draft',
      metaTitle: row.meta_title || '',
      metaDesc: s.metaDescription || row.meta_desc || '',
      keywords: row.keywords || '',
      ogImage: row.og_image || '',
      readMins: Math.max(1, Math.round(String(s.body || '').split(/\s+/).length / 200)),
      publishedAt: row.published_at || '',
      updatedBy: 'system',
    });
    n++;
  }

  if (n) {
    db.log('system', 'blog posts written',
      n + ' draft(s) filled in \u2014 read them and press Publish');
  }
  return n;
}

function run({ db, uploadDir, catalogue, hashPassword, newSalt, password }) {
  if (db.studentByEmail(DEMO_EMAIL)) return null;
  /* A shared test link overrides this, so the three demo accounts are not
     sitting on the internet behind a password anyone can read in the README. */
  const PW = password || DEMO_PASSWORD;

  const csalt = newSalt();
  const counsellor = db.createStudent(COUNSELLOR.email, COUNSELLOR.name, COUNSELLOR.phone,
    hashPassword(PW, csalt), csalt, 'counsellor');

  const asalt = newSalt();
  db.createStudent(ADMIN.email, ADMIN.name, ADMIN.phone,
    hashPassword(PW, asalt), asalt, 'admin');

  const salt = newSalt();
  const s = db.createStudent(DEMO_EMAIL, 'Vishal Sakhamuri', '+919876543210',
    hashPassword(PW, salt), salt);
  db.assignCounsellor(s.id, counsellor.id);

  db.putProfile(s.id, PROFILE);

  /* Five public programmes and two private ones — the same shape the sales page
     hands over after a purchase, so the demo account and a real one differ only
     in how they got there. */
  const pub = catalogue.filter(p => p.isPublic).slice(0, 5);
  const priv = catalogue.filter(p => !p.isPublic).slice(0, 2);
  const chosen = pub.concat(priv);
  /* The office's list — the same shape a purchase hands over. The last two go
     in as the student's own interest, so the demo account shows both lists
     rather than an empty one and a full one. */
  chosen.forEach((p, i) => db.addShortlist(s.id, p, i >= chosen.length - 2 ? 'student' : 'office'));

  chosen.forEach((p, i) => {
    const st = APP_STAGES[i];
    if (st) db.putApplication(s.id, p.id, st[0], st[1]);
  });

  const dir = path.join(uploadDir, String(s.id));
  fs.mkdirSync(dir, { recursive: true });
  DOCS.forEach(([key, filename, title, status]) => {
    const stored = key + '-demo.pdf';
    const buf = placeholderPdf(title);
    fs.writeFileSync(path.join(dir, stored), buf);
    db.addDocument(s.id, key, filename, stored, buf.length);
    if (status === 'ok') db.setDocStatus(s.id, key, 'ok');
  });

  ['daad-study', 'jnmf'].forEach(id => db.saveScholarship(s.id, id));

  db.addOrder({
    studentId: s.id, reference: 'GLV-' + crypto.randomInt(1000, 9999),
    package: 'Roadmap', publicUnis: 5, grossPaise: 999900,
    name: 'Vishal Sakhamuri', email: DEMO_EMAIL, phone: '+919876543210', status: 'paid',
  });

  /* The opening two messages, from the counsellor who is now actually assigned. */
  db.addMessage(s.id, 'them',
    'Hi! I am Kavya, your counsellor for the Germany desk. I have your profile open. '
    + 'Once your documents are verified I will confirm the shortlist with you on a call.', '');
  db.addMessage(s.id, 'them',
    'Two things worth starting now, because they are the slowest: the APS certificate '
    + '(6\u20138 weeks) and your blocked account. Everything else can follow.', '');

  return {
    email: DEMO_EMAIL, password: PW, shortlisted: chosen.length,
    counsellor: COUNSELLOR.email, admin: ADMIN.email, password_all: PW,
  };
}

/*
 * The first real account, for a deployment that must not have demo logins.
 * Created once from ADMIN_EMAIL / ADMIN_PASSWORD; after that the environment
 * variables are only a way back in if the password is lost, and changing them
 * does NOT silently reset a live account's password.
 */
/**
 * The administrator account, and the way back in when its password is lost.
 *
 * ADMIN_PASSWORD creates the account and then, deliberately, stops mattering:
 * a server that silently reset the administrator's password on every restart
 * would mean anyone who can edit an environment variable owns every student
 * file, and it would undo a password changed from inside the application.
 *
 * But that leaves one situation with no way out. The password is generated by
 * the host, shown once in a dashboard, and if it is lost or mistyped there is
 * no second administrator to reset it and no route in. Deleting the disk is
 * not an answer once there are real students on it.
 *
 * So there is a switch: set ADMIN_RESET=true and the existing account's
 * password is set to ADMIN_PASSWORD on the next start, and every session it
 * has open is dropped. It is loud in the log and it is meant to be turned off
 * again immediately — a server left running with it on resets the password on
 * every deploy, which is a foothold rather than a feature.
 */
function seedAdmin({ db, admin, hashPassword, newSalt, reset }) {
  if (!admin || !admin.email || !admin.password) return null;

  const existing = db.studentByEmail(admin.email);
  if (existing) {
    if (!reset) return { existed: true, email: admin.email };

    const salt = newSalt();
    db.setPassword(existing.id, hashPassword(admin.password, salt), salt);
    /* An account that was demoted, or was never an administrator, is put back
       — otherwise the reset lets you in to a screen you cannot use. */
    if (existing.role !== 'admin') db.setRole(existing.id, 'admin');
    db.log('system', 'admin password reset from the environment', admin.email);
    return { reset: true, email: admin.email };
  }

  const salt = newSalt();
  db.createStudent(admin.email, admin.name || 'Glovels Admin', '',
    hashPassword(admin.password, salt), salt, 'admin');
  db.log('system', 'admin account created', admin.email);
  return { created: true, email: admin.email };
}

/*
 * Every university row gets told whether applying through us costs anything.
 *
 * The screens used to filter on public-versus-private, which is a German
 * distinction: of 171 rows, 153 are German public places and the other six
 * destinations have no public row between them. So "Public only" on Canada
 * returned nothing, and a package promising five public universities
 * delivered nothing to anybody not going to Germany.
 *
 * The starting answer is read off what each row already says — we are partnered
 * with the private places, so applying to one costs a student nothing, and the
 * public ones are the names a package buys. That is a starting point rather
 * than a verdict: the column is on the catalogue sheet, so the office corrects
 * any row by uploading it, and a university we later partner with becomes free
 * by changing one cell.
 */
function everyRowSaysWhatItCosts({ db }) {
  if (db.content('feeModelV1')) return 0;
  db.setContent('feeModelV1', { done: true }, 'system');

  let n = 0;
  db.programmes(true).forEach(r => {
    if (r.fee_model === 'free' || r.fee_model === 'package') return;
    db.setFeeModel(r.id, r.is_public ? 'package' : 'free');
    n++;
  });
  if (n) db.log('system', 'Application cost set on every programme', n + ' rows');
  return n;
}

/*
 * And the same 171 rows, told the right way round.
 *
 * The migration above ran once already, with "free" meaning tuition-free
 * rather than free to apply. It wrote Free onto every German public row — the
 * rows whose names nobody can read without a package — and Charged onto the
 * private ones a student can apply to today for nothing. The finder then split
 * its two tabs on that column and put every row under the opposite heading.
 *
 * So this corrects what the first pass wrote, and only that: a row is flipped
 * only where it still holds exactly what the old rule would have given it. A
 * row the office has since set by hand disagrees with that rule and is left
 * alone, which is the whole reason for checking rather than overwriting.
 */
function feeModelIsFreeToApply({ db }) {
  if (db.content('feeModelV2')) return 0;

  let n = 0;
  db.programmes(true).forEach(r => {
    const wroteBefore = r.is_public ? 'free' : 'package';
    if (r.fee_model !== wroteBefore) return;
    db.setFeeModel(r.id, r.is_public ? 'package' : 'free');
    n++;
  });
  /* Marked done AFTER the work, not before it. Writing the flag first means a
     migration that throws half way through is never attempted again — which is
     exactly what happened to the first draft of this one, and it looked from
     the outside like a migration that ran and did nothing. */
  db.setContent('feeModelV2', { done: true }, 'system');
  if (n) db.log('system', 'Application cost corrected on every programme', n + ' rows');
  return n;
}

/*
 * Packages belong to a destination.
 *
 * Everything on the pricing section was built for Germany: four packages, all
 * of them about public universities, all of them promising to reveal names
 * that only German public places have. A student going to Ireland saw the same
 * four and could buy one that could not serve them.
 *
 * So there are two study tabs now — Germany, and Other countries — and the one
 * that opens follows the destination the visitor has already chosen. The four
 * German packages are untouched: same ids, same prices, same copy. What is new
 * is the second tab and the three cards on it.
 *
 * The ladder, after Vishal asked what I thought of his first draft and told me
 * to change it as I saw fit. His draft had five tiers and one of them was
 * dominated: ₹2,999 for check-and-assist on five universities cost MORE than
 * ₹1,999 for doing one end to end, so anybody comparing the two picked the
 * cheaper better one. Three tiers, each strictly better than the one below:
 *
 *   ₹999    we check and advise, THEY file      up to 5 universities
 *   ₹1,999  we write and file everything        1 university
 *   ₹4,999  we write and file everything        3 universities
 *
 * The generous count sits on the cheap tier deliberately: checking five
 * applications costs us almost nothing next to filing one, so it makes ₹999 a
 * real entry point rather than a token.
 *
 * `unlocks` is 0 on all three. It is the public-university name gate, and the
 * six other destinations have no public row to gate — these are service
 * packages, not reveal packages. `matches` is what the student gets picked for
 * them, and it is bounded by their own destination now that the matcher no
 * longer relaxes country.
 */
const OTHER_COUNTRY_PACKAGES = [
  {
    id: 'pkg-assist', tab: 'other', sort: 1, title: 'Assist',
    desc: 'We read everything before it goes and tell you what to fix. You file '
      + 'the applications yourself, to as many as five universities.',
    features: [
      'Up to 5 universities checked before you send them',
      'Every document read against what that university actually asks for',
      'Your SOP and CV marked up, in writing',
      'A 30-minute call to go through the corrections',
      'You file the applications yourself',
    ],
    sell: true, priceInr: 999, priceFrom: '', priceNote: 'one-time',
    unlocks: 0, matches: 5,
    cta: 'Choose Assist',
    consent: 'This gives you up to five universities checked before you apply, your '
      + 'documents read against each one, your SOP and CV marked up, and a 30-minute '
      + 'call. We do not write your application or file it for you, and it does not '
      + 'include visa work or any admission.',
  },
  {
    id: 'pkg-apply-one', tab: 'other', sort: 2, title: 'Complete — one university',
    desc: 'One university, done end to end. We write it, we file it, we chase it.',
    features: [
      '1 university, chosen with a counsellor',
      'Your SOP and CV written to that university, not a template',
      'The application filed by us, on time',
      'Followed up until there is a decision',
      'Document checklist kept current as they ask for things',
    ],
    sell: true, priceInr: 1999, priceFrom: '', priceNote: 'one-time',
    unlocks: 0, matches: 1,
    cta: 'Choose Complete',
    consent: 'This covers one university application written and filed by us and '
      + 'followed up until a decision. It does not include visa work, and no '
      + 'admission is guaranteed.',
  },
  {
    id: 'pkg-apply-three', tab: 'other', sort: 3, title: 'Complete — three universities',
    desc: 'Three universities, all done end to end. The third is effectively half '
      + 'price against taking them one at a time.',
    ribbon: 'Most chosen',
    features: [
      '3 universities, chosen with a counsellor',
      'Each application written to that university, not a template',
      'All three filed by us, on time',
      'Followed up until there is a decision on each',
      'Scholarship and funding options gone through once you have an offer',
    ],
    sell: true, priceInr: 4999, priceFrom: '', priceNote: 'one-time',
    unlocks: 0, matches: 3,
    cta: 'Choose Complete',
    consent: 'This covers three university applications written and filed by us and '
      + 'followed up until a decision. It does not include visa work, and no '
      + 'admission is guaranteed.',
  },
];

function packagesBelongToADestination({ db }) {
  if (db.content('destinationPackagesV1')) return 0;
  db.setContent('destinationPackagesV1', { done: true }, 'system');

  const live = db.content('packages');
  if (!live || !Array.isArray(live.items)) return 0;   /* first run seeds it whole */

  const tabs = Array.isArray(live.tabs) && live.tabs.length
    ? live.tabs.map(t => ({ key: t.key, label: t.label }))
    : [{ key: 'study', label: 'Study' }, { key: 'work', label: 'Work' },
       { key: 'migrate', label: 'Migration' }];

  /* The study tab is Germany's. Renamed only if nobody has renamed it already —
     an office edit outranks a migration. */
  const study = tabs.find(t => t.key === 'study');
  if (study && /^study$/i.test(String(study.label || '').trim())) study.label = 'Germany';

  let added = 0;
  if (!tabs.some(t => t.key === 'other')) {
    const at = tabs.findIndex(t => t.key === 'study');
    tabs.splice(at < 0 ? 0 : at + 1, 0, { key: 'other', label: 'Other countries' });
    added++;
  }

  const have = new Set(live.items.map(x => String(x.id)));
  const fresh = OTHER_COUNTRY_PACKAGES.filter(x => !have.has(String(x.id)));
  const items = live.items.concat(fresh);

  if (!added && !fresh.length && !(study && study.label === 'Germany')) return 0;
  db.setContent('packages', Object.assign({}, live, { tabs, items }), 'system');
  db.log('system', 'Packages scoped to a destination',
    fresh.length + ' package(s) for the other six countries, on their own tab');
  return fresh.length || added;
}

module.exports = { run, seedCatalogue, seedAdmin, seedPosts, bumpBrowseCaps,
  addMissingServices,
  addEntryTiers,
  moveEntryTiersToServices,
  fixCheapestPackagePrice,
  packagesDeliverWhatTheyUnlock,
  removeTheCardsThatWereSourceCode,
  chipsAskWhatItWas,
  everyRowSaysWhatItCosts,
  feeModelIsFreeToApply,
  packagesBelongToADestination,
  openOnRequestServices,
  fillEmptyPosts,
  DEMO_EMAIL, DEMO_PASSWORD };
